import 'package:flutter/material.dart';
import '../model/Category.dart';
import '../model/FoodRecipeContent.dart';

const List<Category> Dummy_Categories = const [
  Category(id: 'E1', title: 'Italien', color: Colors.amber),
  Category(id: 'E2', title: 'Hamburgers', color: Colors.red),
  Category(id: 'E3', title: 'French', color: Colors.green),
  Category(id: 'E4', title: 'Summer', color: Colors.lime),
  Category(id: 'E5', title: 'Asian', color: Colors.pink),
  Category(id: 'E6', title: 'Chinese', color: Color.fromARGB(255, 255, 17, 0)),
  Category(id: 'E7', title: 'Chips', color: Color.fromARGB(255, 252, 231, 0)),
  Category(
      id: 'E8',
      title: 'Japanese Cuisine',
      color: Color.fromARGB(255, 1, 82, 3)),
  Category(
      id: 'E9',
      title: 'Mexican Cuisine ',
      color: Color.fromARGB(255, 98, 0, 0)),
  Category(id: 'E10', title: 'Spicy', color: Color.fromARGB(255, 75, 0, 122)),
  Category(
      id: 'E11', title: 'Spenish', color: Color.fromARGB(255, 255, 143, 7)),
  Category(
      id: 'E12',
      title: 'American Hungryy',
      color: Color.fromARGB(255, 54, 244, 238)),
];

const List<FoodRecipeContent> Recipes = const [
  FoodRecipeContent(
      id: 'f1',
      categories: ['E1', 'E3'],
      title: 'Margherita Pizza',
      image_URL:
          'https://www.tasteatlas.com/images/dishes/1501b7a18cab4f97b3cb834157712052.jpg',
      ingradients: [
        'Pizza dough',
        'Tomato sauce',
        'Mozzarella cheese',
        'Fresh basil leaves',
        'Olive oil',
        'Salt'
      ],
      steps: [
        'Preheat oven to 475°F.',
        'Roll out pizza dough.',
        'Spread tomato sauce.',
        'Add mozzarella cheese.',
        'Top with basil leaves.',
        'Drizzle with olive oil.',
        'Sprinkle salt.',
        'Bake for 10-12 minutes.',
        'Slice and serve hot'
      ],
      duration: 45,
      complexity: Complexity.Medium,
      affordability: Affordability.Pricey,
      isGlutenFree: false,
      isLactoseFree: false,
      isNonVeg: true,
      isVegeterian: false),
  FoodRecipeContent(
      id: 'f2',
      categories: ['E2', 'E5'],
      title: ' Classic Bacon Cheeseburger',
      image_URL:
          'https://d9hyo6bif16lx.cloudfront.net/live/img/production/detail/menu/lunch-dinner_burgers_bacon-cheeseburger.jpg',
      ingradients: [
        'Ground beef',
        'Hamburger buns',
        'Bacon slices',
        'Cheddar cheese slices',
        'Lettuce leaves',
        'Sliced tomatoes',
        'Sliced onions',
        'Pickles',
        'Ketchup',
        'Mustard',
        'Salt',
        'Pepper'
      ],
      steps: [
        'Preheat grill or pan',
        'Shape beef into patties',
        'Season with salt, pepper',
        'Grill or cook patties',
        'Cook bacon until crispy',
        'Toast hamburger buns',
        'Melt cheddar cheese on patties',
        'Assemble burgers with lettuce, tomatoes, onions, pickles',
        'Spread ketchup and mustard',
        'Place patty on bun',
        'Serve hot and enjoy!'
      ],
      duration: 35,
      complexity: Complexity.Medium,
      affordability: Affordability.Pricey,
      isGlutenFree: false,
      isLactoseFree: false,
      isNonVeg: false,
      isVegeterian: true),
  FoodRecipeContent(
    id: 'f3',
    categories: ['E3', 'E7', 'E5'],
    title: 'Ratatouille',
    image_URL:
        'https://klopotenko.com/wp-content/uploads/2019/08/ratatouille_web_eng-1000x600.jpg',
    ingradients: [
      'Eggplant',
      'Zucchini',
      'Bell peppers',
      'Tomatoes',
      'Onions',
      'Garlic cloves',
      'Olive oil',
      'Herbs de Provence',
      'Salt',
      'Pepper'
    ],
    steps: [
      'Slice eggplant, zucchini',
      'Dice bell peppers, tomatoes',
      'Sauté onions, garlic',
      'Add eggplant, zucchini',
      'Stir in bell peppers',
      'Mix in diced tomatoes',
      'Drizzle with olive oil',
      'Season with herbs de Provence, salt, pepper',
      'Simmer until vegetables are tender',
      'Serve hot and enjoy!'
    ],
    duration: 50,
    complexity: Complexity.Simply,
    affordability: Affordability.Affordable,
    isGlutenFree: false,
    isLactoseFree: false,
    isNonVeg: false,
    isVegeterian: true,
  ),
  FoodRecipeContent(
    id: 'f4',
    categories: ['E4', 'E6'],
    title: 'Watermelon Feta Salad',
    image_URL: 'https://toriavey.com/images/2011/06/IMG_9502-2-1-960x720.jpg',
    ingradients: [
      'Watermelon cubes',
      'Feta cheese crumbles',
      'Cucumber slices',
      'Fresh mint leaves',
      'Red onion',
      'Lime juice',
      'Olive oil',
      'Salt',
      'Black pepper'
    ],
    steps: [
      'Combine watermelon, cucumber',
      'Add feta cheese crumbles',
      'Toss in fresh mint leaves',
      'Thinly slice red onion',
      'Drizzle lime juice over',
      'Drizzle olive oil over',
      'Season with salt, black pepper',
      'Gently toss to combine',
      'Chill before serving',
      'Serve cold and enjoy!'
    ],
    duration: 45,
    complexity: Complexity.Simply,
    affordability: Affordability.Affordable,
    isGlutenFree: false,
    isLactoseFree: true,
    isNonVeg: false,
    isVegeterian: true,
  ),
  FoodRecipeContent(
    id: 'f5',
    categories: [
      'E5'
          'E1'
    ],
    title: ' Pad Thai',
    image_URL:
        'https://images.food52.com/LV0uKu3J7fURxElikeJ5M5HAtq8=/1008x672/filters:format(webp)/f0917df7-8286-44ab-b437-e8d0d291e11f--2019-1119_pad-thai_3x2_rocky-luten_003.jpg',
    ingradients: [
      'Rice noodles',
      'Shrimp',
      'Tofu',
      'Bean sprouts',
      'Eggs',
      'Green onions',
      'Garlic',
      'Peanuts',
      'Lime wedges',
      'Fish sauce',
      'Soy sauce',
      'Tamarind paste',
      'Sugar',
      'Red chili flakes'
    ],
    steps: [
      'Soak rice noodles',
      'Cook shrimp and tofu',
      'Sauté garlic and eggs',
      'Add soaked rice noodles',
      'Stir in bean sprouts',
      'Mix in green onions',
      'Add cooked shrimp and tofu',
      'Prepare sauce with fish sauce, soy sauce, tamarind paste, sugar',
      'Pour sauce over noodles',
      'Toss to combine',
      'Garnish with crushed peanuts',
      'Serve with lime wedges',
      'Sprinkle with red chili flakes',
      'Enjoy this flavorful dish!'
    ],
    duration: 60,
    complexity: Complexity.Medium,
    affordability: Affordability.Pricey,
    isGlutenFree: true,
    isLactoseFree: false,
    isNonVeg: false,
    isVegeterian: true,
  ),
  FoodRecipeContent(
    id: 'f6',
    categories: ['E6', 'E8'],
    title: 'Kung Pao Chicken',
    image_URL:
        'https://www.savorytooth.com/wp-content/uploads/2018/05/kung-pao-chicken-5.jpg',
    ingradients: [
      'Chicken breast',
      'Bell peppers',
      'Roasted peanuts',
      'Dried red chilies',
      'Garlic cloves',
      'Ginger',
      'Soy sauce',
      'Rice vinegar',
      'Cornstarch',
      'Sesame oil',
      'Sugar',
      'Salt',
      'Scallions'
    ],
    steps: [
      'Cut chicken into cubes',
      'Slice bell peppers',
      'Crush roasted peanuts',
      'Soak dried red chilies',
      'Mince garlic and ginger',
      'Prepare sauce with soy sauce, rice vinegar, cornstarch, sesame oil, sugar, salt',
      'Heat oil in a pan',
      'Sauté chicken cubes',
      'Add garlic, ginger, dried red chilies',
      'Stir in bell peppers',
      'Pour in sauce mixture',
      'Toss in roasted peanuts',
      'Garnish with chopped scallions',
      'Serve hot and enjoy!'
    ],
    duration: 60,
    complexity: Complexity.Medium,
    affordability: Affordability.Pricey,
    isGlutenFree: true,
    isLactoseFree: false,
    isNonVeg: true,
    isVegeterian: false,
  ),
  FoodRecipeContent(
    id: 'f7',
    categories: ['E7', 'E5'],
    title: 'Homemade Potato Chips',
    image_URL:
        'https://www.savorytooth.com/wp-content/uploads/2018/05/kung-pao-chicken-5.jpg',
    ingradients: [
      'Watermelon cubes',
      'Feta cheese crumbles',
      'Cucumber slices',
      'Fresh mint leaves',
      'Red onion',
      'Lime juice',
      'Olive oil',
      'Salt',
      'Black pepper'
    ],
    steps: [
      'Combine watermelon, cucumber',
      'Add feta cheese crumbles',
      'Toss in fresh mint leaves',
      'Thinly slice red onion',
      'Drizzle lime juice over',
      'Drizzle olive oil over',
      'Season with salt, black pepper',
      'Gently toss to combine',
      'Chill before serving',
      'Serve cold and enjoy!'
    ],
    duration: 40,
    complexity: Complexity.Simply,
    affordability: Affordability.Pricey,
    isGlutenFree: true,
    isLactoseFree: false,
    isNonVeg: false,
    isVegeterian: true,
  ),
  FoodRecipeContent(
    id: 'f8',
    categories: ['E8', 'E11'],
    title: 'Chicken Teriyaki',
    image_URL:
        'https://images.themodernproper.com/billowy-turkey/production/posts/2019/TeriyakiChicken_5.jpg?w=1800&q=82&fm=jpg&fit=crop&dm=1673480382&s=5539db8ffb2c2faaf0ccc173648614b8',
    ingradients: [
      'Chicken thighs',
      'Soy sauce',
      'Mirin',
      'Sake',
      'Sugar',
      'Garlic',
      'Ginger',
      'Vegetable oil',
      'Green onions'
    ],
    steps: [
      'Slice chicken thighs',
      'Combine soy sauce, mirin, sake, and sugar in a bowl',
      'Mince garlic and ginger',
      'Marinate chicken in sauce',
      'Heat vegetable oil in a pan',
      'Sear chicken on both sides',
      'Pour remaining marinade over chicken',
      'Cover and simmer until chicken is cooked through',
      'Remove chicken from the pan',
      'Reduce the sauce to desired consistency',
      'Slice green onions for garnish',
      'Serve chicken with sauce',
      'Sprinkle with sliced green onions',
      'Enjoy with steamed rice or vegetables'
    ],
    duration: 45,
    complexity: Complexity.Medium,
    affordability: Affordability.Pricey,
    isGlutenFree: false,
    isLactoseFree: false,
    isNonVeg: true,
    isVegeterian: false,
  ),
  FoodRecipeContent(
    id: 'f9',
    categories: ['E9', 'E3'],
    title: 'Chicken Enchiladas',
    image_URL:
        'https://i0.wp.com/www.skiptomylou.org/wp-content/uploads/2018/04/chicken-enchilada-recipe-800x533.jpg',
    ingradients: [
      'Chicken breast',
      'Tortillas',
      'Enchilada sauce',
      'Cheese',
      'Onions',
      'Bell peppers',
      'Cilantro',
      'Sour cream',
      'Oil',
      'Salt',
      'Pepper'
    ],
    steps: [
      'Cook and shred chicken',
      'Preheat oven to 350°F',
      'Warm tortillas in oven',
      'Sauté onions and bell peppers',
      'Mix shredded chicken with sautéed vegetables',
      'Season with salt and pepper',
      'Spread enchilada sauce in a baking dish',
      'Fill tortillas with chicken mixture',
      'Roll tortillas and place in the dish',
      'Pour more enchilada sauce over the rolled tortillas',
      'Sprinkle cheese on top',
      'Bake for 20-25 minutes',
      'Garnish with cilantro',
      'Serve with sour cream'
    ],
    duration: 45,
    complexity: Complexity.Simply,
    affordability: Affordability.Affordable,
    isGlutenFree: false,
    isLactoseFree: true,
    isNonVeg: false,
    isVegeterian: true,
  ),
  FoodRecipeContent(
    id: 'f10',
    categories: ['E10', 'E12', 'E5'],
    title: 'Spicy Thai Basil Chicken',
    image_URL:
        'https://www.allrecipes.com/thmb/pCqIIVuO21ZI32qhXHuKPKioA3k=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/RM-145572-ThaiSpicyBasilChickenFriedRice-ddmfs-3x4-6479-bf3154d3e39e4505b269a1c32b5abfba.jpg',
    ingradients: [
      'Chicken breast',
      'Thai basil leaves',
      'Bird\'s eye chili',
      'Garlic cloves',
      'Fish sauce',
      'Soy sauce',
      'Oyster sauce',
      'Sugar',
      'Vegetable oil',
      'Onion',
      'Bell peppers',
      'Salt',
      'Black pepper'
    ],
    steps: [
      'Slice chicken breast',
      'Chop Thai basil leaves',
      'Mince bird\'s eye chili',
      'Crush garlic cloves',
      'Combine fish sauce, soy sauce, oyster sauce, and sugar in a bowl',
      'Heat vegetable oil in a pan',
      'Sauté minced garlic and chili',
      'Add sliced chicken and cook until done',
      'Stir in onion and bell peppers',
      'Pour the sauce mixture over the chicken and vegetables',
      'Season with salt and black pepper',
      'Cook for a few more minutes until everything is well coated and heated through',
      'Sprinkle chopped Thai basil leaves',
      'Serve hot with steamed rice'
    ],
    duration: 60,
    complexity: Complexity.Hard,
    affordability: Affordability.Luxeries,
    isGlutenFree: false,
    isLactoseFree: false,
    isNonVeg: true,
    isVegeterian: false,
  ),
  FoodRecipeContent(
    id: 'f11',
    categories: ['E11', 'E7', 'E4'],
    title: 'Paella',
    image_URL:
        'https://www.allrecipes.com/thmb/pCqIIVuO21ZI32qhXHuKPKioA3k=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/RM-145572-ThaiSpicyBasilChickenFriedRice-ddmfs-3x4-6479-bf3154d3e39e4505b269a1c32b5abfba.jpg',
    ingradients: [
      'Chicken pieces',
      'Shrimp',
      'Mussels',
      'Saffron threads',
      'Rice',
      'Bell peppers',
      'Onion',
      'Garlic cloves',
      'Tomato',
      'Chicken broth',
      'Olive oil',
      'Paprika',
      'Salt',
      'Black pepper',
      'Lemon wedges'
    ],
    steps: [
      'Heat olive oil',
      'Sauté chicken pieces',
      'Add shrimp and mussels',
      'Remove and set aside',
      'Sauté chopped onions, bell peppers, and garlic',
      'Add diced tomato',
      'Stir in rice and saffron threads',
      'Pour in chicken broth',
      'Season with paprika, salt, and black pepper',
      'Simmer until rice is cooked and liquid is absorbed',
      'Return chicken, shrimp, and mussels to the pan',
      'Cover and let sit for a few minutes',
      'Garnish with lemon wedges',
      'Serve hot and enjoy!'
    ],
    duration: 46,
    complexity: Complexity.Hard,
    affordability: Affordability.Luxeries,
    isGlutenFree: false,
    isLactoseFree: false,
    isNonVeg: true,
    isVegeterian: false,
  ),
  FoodRecipeContent(
    id: 'f12',
    categories: ['E12', 'E2', 'E6'],
    title: 'Cheeseburger with Bacon',
    image_URL:
        'https://www.santamariaworld.com/optimized/recipe-large/globalassets/uk/npd/burger-recipe-website.png',
    ingradients: [
      'Ground beef',
      'Hamburger buns',
      'Bacon slices',
      'Cheddar cheese slices',
      'Lettuce leaves',
      'Sliced tomatoes',
      'Sliced onions',
      'Pickles',
      'Ketchup',
      'Mustard',
      'Salt',
      'Pepper'
    ],
    steps: [
      'Preheat grill or pan',
      'Shape ground beef into patties',
      'Season patties with salt and pepper',
      'Cook bacon until crispy',
      'Grill or cook beef patties to desired doneness',
      'Place cheese slices on patties to melt',
      'Toast hamburger buns',
      'Assemble burgers with lettuce, tomatoes, onions, pickles',
      'Spread ketchup and mustard on buns',
      'Add cooked bacon on top',
      'Place beef patty with melted cheese on bun',
      'Serve hot and enjoy!'
    ],
    duration: 50,
    complexity: Complexity.Medium,
    affordability: Affordability.Pricey,
    isGlutenFree: false,
    isLactoseFree: false,
    isNonVeg: false,
    isVegeterian: true,
  ),
];
